AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  This solution consists of a lambda function which which gets triggered when CF stack is deployed. This is used for creating sumologic resources like collector, source and app folders.

Globals:
  Function:
    Timeout: 300

Metadata:
  AWS::ServerlessRepo::Application:
    Author: Sumo Logic
    Description: This solution consists of a lambda function which which gets triggered when CF stack is deployed. This is used for creating sumologic resources like collector, source and app folders.
    HomePageUrl: https://github.com/SumoLogic/sumologic-aws-lambda
    Labels:
      - lambda
      - sumologic
      - serverless
    Name: sumologic-app-utils
    SemanticVersion: 2.0.16
    SourceCodeUrl: https://github.com/SumoLogic/sumologic-aws-lambda/tree/main/sumologic-app-utils
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: ./README.md

Resources:

  SumoAppUtilsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main.handler
      Runtime: python3.12
      CodeUri: s3://appdevstore/sumo_app_utils/v2.0.16/sumo_app_utils.zip
      MemorySize: 128
      Timeout: 300
      Policies:
        - Statement:
            - Action:
                - cloudtrail:CreateTrail
                - cloudtrail:DeleteTrail
                - cloudtrail:UpdateTrail
                - cloudtrail:StartLogging
              Effect: Allow
              Resource: arn:aws:cloudtrail:*:*:*
              Sid: CreateCloudTrailPolicy

Outputs:
  SumoAppUtilsFunction:
    Description: "SumoAppUtils Function ARN"
    Value: !GetAtt SumoAppUtilsFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SumoAppUtilsFunction"

  SumoAppUtilsFunctionRole:
    Description: "SumoAppUtils Function Role ARN"
    Value: !GetAtt SumoAppUtilsFunctionRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SumoAppUtilsFunctionRole"
