AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'This solution consists of a lambda function which which gets triggered
  by CloudWatch events with findings as payload which are then ingested to Sumo Logic

  '
Globals:
  Function:
    Timeout: 300
Metadata:
  AWS::ServerlessRepo::Application:
    Author: Sumo Logic
    Description: This solution consists of a lambda function which which gets triggered
      by CloudWatch events with findings as payload which are then ingested to Sumo
      Logic via HTTP source.
    HomePageUrl: https://github.com/SumoLogic/sumologic-aws-lambda
    Labels:
    - sumologic
    - serverless
    - security
    - cloudwatchevents
    - securityhub
    Name: sumologic-securityhub-connector-aws-org
    LicenseUrl: s3://appdevstore/SecurityHubCollectorAWSOrg/v1.0.4/6092dd6c323e33634657102f570628e0
    ReadmeUrl: s3://appdevstore/SecurityHubCollectorAWSOrg/v1.0.4/eb911876461845db8f3113dbace6d454
    SemanticVersion: 1.0.4
    SourceCodeUrl: https://github.com/SumoLogic/sumologic-aws-lambda/tree/master/securityhub-org/sumologic-securityhub-connector-aws-org
    SpdxLicenseId: Apache-2.0
Parameters:
  SumoEndpoint:
    Description: SumoLogic Endpoint to post logs
    Type: String
Resources:
  SecurityHubCollectorAwsOrg:
    Metadata:
      SkipBuild: true
      cfn_nag:
        rules_to_suppress:
        - id: W89
          reason: Lambda functions should be deployed inside a VPC
      SamResourceId: SecurityHubCollectorAwsOrg
    Type: AWS::Serverless::Function
    Properties:
      Handler: securityhub_collector_org.lambda_handler
      Runtime: python3.11
      CodeUri: s3://appdevstore/SecurityHubCollectorAWSOrg/v1.0.4/777ccb7a25ea254ed6c24e40a08fa709
      MemorySize: 128
      Timeout: 300
      ReservedConcurrentExecutions: 100
      Environment:
        Variables:
          SUMO_ENDPOINT:
            Ref: SumoEndpoint
      Events:
        CloudWatchEventTrigger:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
              - aws.securityhub
Outputs:
  SecurityHubCollectorAwsOrg:
    Description: SecurityHubCollectorAwsOrg Function ARN
    Value:
      Fn::GetAtt:
      - SecurityHubCollectorAwsOrg
      - Arn
